import bcrypt from 'bcryptjs';
import { Plan, Client, ClientSettings, ClientKnowledgeBase, ChannelIntegration, Conversation, LeadOrder, AdminNotification, AuditLog, AdminUser } from './types';

export function getInitialSeedData() {
  const adminUsers: AdminUser[] = [
    {
      id: 'usr_superadmin',
      email: 'admin',
      name: 'Super Administrator',
      role: 'superadmin',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  ];

  const plans: Plan[] = [
    {
      plan_id: 'starter',
      name: 'Starter Tier',
      monthly_chat_limit: 1000,
      allowed_channels: ['whatsapp'],
      allowed_message_types: ['text', 'button', 'interactive'],
      enabled_modules: ['ai', 'leads'],
      lead_fields: ['name', 'phone', 'service'],
      ai_level: 'Basic',
      memory_level: 'Window',
      order_capture: false,
      human_handoff: true,
      storage_level: 'postgres',
      crm_enabled: true,
      is_active: true,
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 86400000).toISOString()
    },
    {
      plan_id: 'professional',
      name: 'Professional Tier',
      monthly_chat_limit: 5000,
      allowed_channels: ['whatsapp', 'messenger', 'instagram'],
      allowed_message_types: ['text', 'image', 'audio', 'document', 'location', 'button', 'interactive'],
      enabled_modules: ['ai', 'leads', 'orders', 'knowledge_base'],
      lead_fields: ['name', 'phone', 'service', 'area', 'notes'],
      ai_level: 'Advanced',
      memory_level: 'Window',
      order_capture: true,
      human_handoff: true,
      storage_level: 'postgres',
      crm_enabled: true,
      is_active: true,
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 86400000).toISOString()
    },
    {
      plan_id: 'enterprise',
      name: 'Enterprise VIP Tier',
      monthly_chat_limit: 25000,
      allowed_channels: ['whatsapp', 'messenger', 'instagram'],
      allowed_message_types: ['text', 'image', 'audio', 'video', 'document', 'location', 'button', 'interactive'],
      enabled_modules: ['ai', 'leads', 'orders', 'knowledge_base', 'custom_webhook', 'analytics'],
      lead_fields: ['name', 'phone', 'service', 'area', 'address', 'booking_date', 'notes'],
      ai_level: 'Custom',
      memory_level: 'Vector',
      order_capture: true,
      human_handoff: true,
      storage_level: 'postgres',
      crm_enabled: true,
      is_active: true,
      created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 86400000).toISOString()
    }
  ];

  const clients: Client[] = [
    {
      client_id: 'client_lumina',
      channel_account_id: '1098800089990621',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      channel: 'whatsapp',
      status: 'active',
      plan_id: 'professional',
      owner_phone: '+1 (555) 234-5678',
      owner_email: 'contact@lumina-clinic.com',
      reply_tone: 'Professional, warm, highly accurate',
      service_type: 'Medical consultations and appointments',
      timezone: 'America/New_York',
      storage_destination: 'postgres',
      crm_webhook_url: 'https://api.lumina-clinic.com/webhooks/leads',
      language: 'en',
      created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      client_id: 'client_zest',
      channel_account_id: '1098800089990622',
      business_name: 'Zest Gourmet Bistro & Lounge',
      channel: 'whatsapp',
      status: 'active',
      plan_id: 'starter',
      owner_phone: '+1 (555) 345-6789',
      owner_email: 'info@zestgourmet.com',
      reply_tone: 'Energetic, welcoming, fast',
      service_type: 'Table reservations and dining',
      timezone: 'America/New_York',
      storage_destination: 'postgres',
      crm_webhook_url: '',
      language: 'en',
      created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
    {
      client_id: 'client_nexus',
      channel_account_id: '1098800089990623',
      business_name: 'Nexus Cloud Technologies',
      channel: 'whatsapp',
      status: 'active',
      plan_id: 'enterprise',
      owner_phone: '+1 (555) 456-7890',
      owner_email: 'hello@nexustech.io',
      reply_tone: 'Technical, consultative, executive',
      service_type: 'Software development & AI solutions',
      timezone: 'America/New_York',
      storage_destination: 'postgres',
      crm_webhook_url: 'https://nexustech.io/api/crm/events',
      language: 'en',
      created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
    {
      client_id: 'client_aura',
      channel_account_id: '1098800089990624',
      business_name: 'Aura Wellness & Spa Retreat',
      channel: 'instagram',
      status: 'paused',
      plan_id: 'professional',
      owner_phone: '+1 (555) 567-8901',
      owner_email: 'bookings@auraspa.com',
      reply_tone: 'Calm, refined, serene',
      service_type: 'Spa therapies and skincare',
      timezone: 'America/New_York',
      storage_destination: 'postgres',
      crm_webhook_url: '',
      language: 'en',
      created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      client_id: 'client_prime',
      channel_account_id: '1098800089990625',
      business_name: 'Prime Real Estate Group',
      channel: 'messenger',
      status: 'suspended',
      plan_id: 'enterprise',
      owner_phone: '+1 (555) 678-9012',
      owner_email: 'sales@primerealestate.com',
      reply_tone: 'Commercial, direct',
      service_type: 'Real estate advisory and sales',
      timezone: 'America/New_York',
      storage_destination: 'postgres',
      crm_webhook_url: '',
      language: 'en',
      created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    }
  ];

  const clientSettings: ClientSettings[] = [
    {
      client_id: 'client_lumina',
      service_description: 'Advanced specialty clinic for cosmetic dentistry, dental implants, and laser skin treatments.',
      pricing_rules: 'Initial dental examination $50. Laser teeth whitening packages start from $180.',
      coverage_rules: 'Downtown Center, Monday to Saturday 9:00 AM - 7:00 PM.',
      booking_requirements: 'Full name, phone number, requested treatment, and preferred time.',
      fallback_response: 'Hello! Your inquiry has been routed to our receptionist desk and we will contact you shortly.',
      escalation_keyword: 'doctor',
      human_agent_phone: '+1 (555) 234-5678',
      booking_required_fields: ['name', 'phone', 'service', 'booking_date']
    },
    {
      client_id: 'client_zest',
      service_description: 'Upscale bistro offering handcrafted dining, artisanal coffee, and fresh Italian cuisine.',
      pricing_rules: 'Lunch special $25 per person. Evening tasting menu $45.',
      coverage_rules: 'West End district. Takeout & delivery available across the metro area.',
      booking_requirements: 'Party size, date, preferred seating (indoor/patio), and dietary notes.',
      fallback_response: 'Welcome to Zest! Please hold while we connect you to our floor manager.',
      escalation_keyword: 'manager',
      human_agent_phone: '+1 (555) 345-6789',
      booking_required_fields: ['name', 'phone', 'service', 'notes']
    },
    {
      client_id: 'client_nexus',
      service_description: 'Enterprise AI and full-stack software development firm specializing in conversational pipelines.',
      pricing_rules: 'Initial architectural discovery session is complimentary. Projects scoped on milestones.',
      coverage_rules: 'Global remote delivery across North America, EMEA, and APAC.',
      booking_requirements: 'Company name, project scope, email, and target timeline.',
      fallback_response: 'Welcome to Nexus! A solutions architect will reach out via email to schedule your discovery call.',
      escalation_keyword: 'engineer',
      human_agent_phone: '+1 (555) 456-7890',
      booking_required_fields: ['name', 'phone', 'service', 'area', 'notes']
    }
  ];

  const knowledgeBase: ClientKnowledgeBase[] = [
    {
      client_id: 'client_lumina',
      section_key: 'Available Services',
      content: 'Laser teeth whitening, instant dental implants, porcelain veneers, and microscopic endodontics.',
      enabled: true
    },
    {
      client_id: 'client_lumina',
      section_key: 'Operating Hours',
      content: 'Monday - Saturday: 9:00 AM - 7:00 PM. Sunday: Closed.',
      enabled: true
    },
    {
      client_id: 'client_zest',
      section_key: 'Coffee & Drinks Menu',
      content: 'Specialty single-origin coffee from Ethiopia and Colombia brewed via V60, Aeropress, and espresso bar.',
      enabled: true
    }
  ];

  const channelIntegrations: ChannelIntegration[] = [
    {
      id: 'int_lumina_wa',
      client_id: 'client_lumina',
      platform: 'whatsapp',
      status: 'CONNECTED',
      external_account_id: '1098800089990621',
      external_account_name: 'Lumina Clinic WhatsApp Official',
      whatsapp_phone_number_id: '1098800089990621',
      waba_id: 'waba_998877665544',
      credential_reference: 'vault:secret:lumina_wa_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 3600000).toISOString(),
      token_expires_at: new Date(Date.now() + 60 * 86400000).toISOString(),
      metadata: { quality_rating: 'GREEN', display_phone: '+1 (555) 234-5678' },
      created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'int_lumina_fb',
      client_id: 'client_lumina',
      platform: 'messenger',
      status: 'CONNECTED',
      external_account_id: '1211325755394127',
      external_account_name: 'Lumina Dental & Aesthetic Center',
      facebook_page_id: '1211325755394127',
      credential_reference: 'vault:secret:lumina_fb_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 3600000).toISOString(),
      created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'int_lumina_ig',
      client_id: 'client_lumina',
      platform: 'instagram',
      status: 'CONNECTED',
      external_account_id: '178414000123456',
      external_account_name: '@lumina_clinic_official',
      instagram_account_id: '178414000123456',
      facebook_page_id: '1211325755394127',
      credential_reference: 'vault:secret:lumina_ig_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 3600000).toISOString(),
      created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'int_zest_wa',
      client_id: 'client_zest',
      platform: 'whatsapp',
      status: 'CONNECTED',
      external_account_id: '1098800089990622',
      external_account_name: 'Zest Restaurant Official',
      whatsapp_phone_number_id: '1098800089990622',
      waba_id: 'waba_112233445566',
      credential_reference: 'vault:secret:zest_wa_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 7200000).toISOString(),
      token_expires_at: new Date(Date.now() + 45 * 86400000).toISOString(),
      metadata: { quality_rating: 'GREEN', display_phone: '+1 (555) 345-6789' },
      created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'int_nexus_fb',
      client_id: 'client_nexus',
      platform: 'messenger',
      status: 'CONNECTED',
      external_account_id: 'page_987654321',
      external_account_name: 'Nexus Cloud Technologies Page',
      facebook_page_id: 'page_987654321',
      credential_reference: 'vault:secret:nexus_fb_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 1800000).toISOString(),
      token_expires_at: new Date(Date.now() + 50 * 86400000).toISOString(),
      metadata: { page_category: 'Information Technology' },
      created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: 'int_nexus_ig',
      client_id: 'client_nexus',
      platform: 'instagram',
      status: 'CONNECTED',
      external_account_id: 'ig_17841400987654',
      external_account_name: '@nexustech.official',
      instagram_account_id: 'ig_17841400987654',
      facebook_page_id: 'page_987654321',
      credential_reference: 'vault:secret:nexus_ig_token',
      webhook_status: 'verified_active',
      last_validated_at: new Date(Date.now() - 1800000).toISOString(),
      token_expires_at: new Date(Date.now() + 50 * 86400000).toISOString(),
      metadata: { followers_count: 14200 },
      created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      id: 'int_aura_ig',
      client_id: 'client_aura',
      platform: 'instagram',
      status: 'EXPIRED',
      external_account_id: 'ig_17841400123456',
      external_account_name: '@auraspa.retreat',
      instagram_account_id: 'ig_17841400123456',
      facebook_page_id: 'page_123456789',
      credential_reference: 'vault:secret:aura_ig_token',
      webhook_status: 'error_auth_expired',
      last_validated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
      token_expires_at: new Date(Date.now() - 2 * 86400000).toISOString(),
      last_error: 'OAuthAccessTokenException: Session has expired or token was revoked.',
      created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      id: 'int_prime_wa',
      client_id: 'client_prime',
      platform: 'whatsapp',
      status: 'DISCONNECTED',
      external_account_id: '1098800089990625',
      external_account_name: 'Prime Properties WhatsApp',
      whatsapp_phone_number_id: '1098800089990625',
      waba_id: 'waba_554433221100',
      credential_reference: '',
      webhook_status: 'inactive',
      last_validated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
      last_error: 'Client suspended due to billing delinquency.',
      created_at: new Date(Date.now() - 48 * 86400000).toISOString(),
      updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    }
  ];

  const nowMonth = new Date().toISOString().slice(0, 7); // e.g. "2026-08"

  const usageCounters = [
    { client_id: 'client_lumina', month: nowMonth, used_chats: 3890, monthly_limit: 5000 },
    { client_id: 'client_zest', month: nowMonth, used_chats: 920, monthly_limit: 1000 },
    { client_id: 'client_nexus', month: nowMonth, used_chats: 8450, monthly_limit: 25000 },
    { client_id: 'client_aura', month: nowMonth, used_chats: 410, monthly_limit: 5000 },
    { client_id: 'client_prime', month: nowMonth, used_chats: 25400, monthly_limit: 25000 },
  ];

  const conversations: Conversation[] = [
    {
      id: 1,
      client_id: 'client_lumina',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      customer_id: '15558889901',
      from_phone: '+15558889901',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3ODg4ODg5OTAxdW==',
      message_type: 'text',
      message_text: 'Hi, I would like to inquire about laser teeth whitening appointment slots',
      public_customer_reply: 'Hello and welcome to Lumina Clinic! Our laser teeth whitening packages start from $180 including a free consultation and full checkup. Would you prefer a morning or afternoon appointment?',
      direction: 'inbound',
      block_reason: '',
      order_confirmed: false,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    },
    {
      id: 2,
      client_id: 'client_lumina',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      customer_id: '15558889901',
      from_phone: '+15558889901',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3ODg4ODg5OTAydW==',
      message_type: 'text',
      message_text: 'Next Thursday at 4:00 PM works great for Rachel Green',
      public_customer_reply: 'Your appointment is confirmed for Thursday at 4:00 PM with Dr. Sarah for Rachel Green. We look forward to seeing you!',
      direction: 'inbound',
      block_reason: '',
      order_confirmed: true,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    },
    {
      id: 3,
      client_id: 'client_zest',
      business_name: 'Zest Gourmet Bistro & Lounge',
      customer_id: '15559991122',
      from_phone: '+15559991122',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3OTk5OTkxMTIxdW==',
      message_type: 'text',
      message_text: 'Good evening, can we reserve a table for 5 people tonight at 8:30 PM?',
      public_customer_reply: 'Good evening and welcome! We would be delighted to host you. We have a great patio table available. Could you provide a name for the reservation?',
      direction: 'inbound',
      block_reason: '',
      order_confirmed: false,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 50 * 60000).toISOString(),
    },
    {
      id: 4,
      client_id: 'client_zest',
      business_name: 'Zest Gourmet Bistro & Lounge',
      customer_id: '15559991122',
      from_phone: '+15559991122',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3OTk5OTkxMTIydW==',
      message_type: 'text',
      message_text: 'Yes under Michael Scott, thank you so much!',
      public_customer_reply: 'Thank you Michael! Table for 5 tonight at 8:30 PM is confirmed under Michael Scott. See you soon!',
      direction: 'inbound',
      block_reason: '',
      order_confirmed: true,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 42 * 60000).toISOString(),
    },
    {
      id: 5,
      client_id: 'client_nexus',
      business_name: 'Nexus Cloud Technologies',
      customer_id: 'ig_usr_55667788',
      from_phone: '+15550123456',
      channel: 'instagram',
      message_id: 'mid.IG_msg_11223344',
      message_type: 'text',
      message_text: 'Hi, we are looking to build a custom AI chatbot for our logistics platform in Dubai.',
      public_customer_reply: 'Hello! Thank you for reaching out to Nexus Tech Solutions. We specialize in enterprise AI pipelines and multi-agent systems. Could you share your contact phone/email so our enterprise architecture team can schedule a discovery session?',
      direction: 'inbound',
      block_reason: '',
      order_confirmed: false,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 120 * 60000).toISOString(),
    },
    {
      id: 6,
      client_id: 'client_prime',
      business_name: 'Prime Real Estate Group',
      customer_id: 'fb_usr_998811',
      from_phone: '',
      channel: 'messenger',
      message_id: 'mid.FB_msg_778899',
      message_type: 'text',
      message_text: 'Hi, I would like information regarding the luxury penthouses available for sale',
      public_customer_reply: 'Service temporarily unavailable due to account maintenance.',
      direction: 'inbound',
      block_reason: 'client_suspended',
      order_confirmed: false,
      current_month: nowMonth,
      created_at: new Date(Date.now() - 300 * 60000).toISOString(),
    }
  ];

  const leadsOrders: LeadOrder[] = [
    {
      id: 1,
      client_id: 'client_lumina',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      customer_id: '15558889901',
      from_phone: '+15558889901',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3ODg4ODg5OTAydW==',
      message_type: 'text',
      message_text: 'Next Thursday at 4:00 PM works great for Rachel Green',
      public_customer_reply: 'Your appointment is confirmed for Thursday at 4:00 PM.',
      order_confirmed: true,
      lead_status: 'booked',
      order_status: 'confirmed',
      order_payload: {
        customer_name: 'Rachel Green',
        phone: '+15558889901',
        service: 'Laser Whitening & Dental Exam',
        area: 'Downtown Medical Center',
        booking_date: '2026-08-27',
        booking_time: '16:00',
        amount: 180,
        notes: 'Patient requested Dr. Sarah'
      },
      assigned_staff: 'Dr. Sarah',
      notes: 'Booking confirmed and directions sent via WhatsApp',
      current_month: nowMonth,
      created_at: new Date(Date.now() - 15 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 10 * 60000).toISOString(),
    },
    {
      id: 2,
      client_id: 'client_zest',
      business_name: 'Zest Gourmet Bistro & Lounge',
      customer_id: '15559991122',
      from_phone: '+15559991122',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3OTk5OTkxMTIydW==',
      message_type: 'text',
      message_text: 'Yes under Michael Scott, thank you so much!',
      public_customer_reply: 'Table for 5 tonight at 8:30 PM is confirmed.',
      order_confirmed: true,
      lead_status: 'booked',
      order_status: 'confirmed',
      order_payload: {
        customer_name: 'Michael Scott',
        phone: '+15559991122',
        service: 'Patio Table for 5',
        area: 'West End District',
        booking_date: '2026-08-26',
        booking_time: '20:30',
        amount: 0,
        notes: 'Outdoor patio table - Birthday setup'
      },
      assigned_staff: 'Alex - Floor Manager',
      notes: 'Assigned Table 14 on the terrace',
      current_month: nowMonth,
      created_at: new Date(Date.now() - 42 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 30 * 60000).toISOString(),
    },
    {
      id: 3,
      client_id: 'client_nexus',
      business_name: 'Nexus Cloud Technologies',
      customer_id: 'ig_usr_55667788',
      from_phone: '+15550123456',
      channel: 'instagram',
      message_id: 'mid.IG_msg_11223344',
      message_type: 'text',
      message_text: 'Hi, we are looking to build a custom AI chatbot for our logistics platform in Dubai.',
      public_customer_reply: 'Could you share your contact phone/email so our team can schedule a discovery session?',
      order_confirmed: false,
      lead_status: 'qualified',
      order_status: 'pending',
      order_payload: {
        customer_name: 'Kareem Mansour',
        phone: '+15550123456',
        service: 'Enterprise AI Logistics System',
        area: 'Dubai, UAE',
        notes: 'Budget > $15k, target Q4 launch'
      },
      assigned_staff: 'Eng. Omar',
      notes: 'Scheduled initial Zoom discovery session for Thursday 2 PM',
      current_month: nowMonth,
      created_at: new Date(Date.now() - 110 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 60000).toISOString(),
    },
    {
      id: 4,
      client_id: 'client_lumina',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      customer_id: '15557771122',
      from_phone: '+15557771122',
      channel: 'whatsapp',
      message_id: 'wamid.HBgNNjI3NzcxMTIyMzN1==',
      message_type: 'text',
      message_text: 'I would like to ask about porcelain veneers and treatment duration',
      public_customer_reply: 'Hello! Porcelain veneers start from $350 per tooth with complete digital smile design.',
      order_confirmed: false,
      lead_status: 'contacted',
      order_status: 'pending',
      order_payload: {
        customer_name: 'Diana Prince',
        phone: '+15557771122',
        service: 'Veneers Consultation',
        area: 'Uptown'
      },
      assigned_staff: 'Main Desk',
      notes: 'Customer requested a follow-up call tomorrow morning',
      current_month: nowMonth,
      created_at: new Date(Date.now() - 360 * 60000).toISOString(),
      updated_at: new Date(Date.now() - 180 * 60000).toISOString(),
    }
  ];

  const adminNotifications: AdminNotification[] = [
    {
      id: 1,
      client_id: 'client_lumina',
      business_name: 'Lumina Dental & Aesthetic Clinic',
      owner_phone: '+1 (555) 234-5678',
      event_type: 'confirmed_order',
      block_reason: '',
      lead_status: 'booked',
      order_confirmed: true,
      customer_id: '15558889901',
      from_phone: '+15558889901',
      summary: 'Confirmed Booking: Rachel Green - Laser Whitening & Dental Exam (2026-08-27 16:00)',
      payload: { amount: 180, service: 'Laser Whitening & Dental Exam' },
      is_read: false,
      created_at: new Date(Date.now() - 15 * 60000).toISOString()
    },
    {
      id: 2,
      client_id: 'client_aura',
      business_name: 'Aura Wellness & Spa Retreat',
      owner_phone: '+1 (555) 567-8901',
      event_type: 'channel_auth_expired',
      block_reason: 'token_expired',
      lead_status: '',
      order_confirmed: false,
      customer_id: '',
      from_phone: '',
      summary: 'Security Alert: Instagram Access Token expired for Aura Wellness & Spa. Reconnect required.',
      payload: { platform: 'instagram', last_error: 'OAuthAccessTokenException' },
      is_read: false,
      created_at: new Date(Date.now() - 2 * 86400000).toISOString()
    },
    {
      id: 3,
      client_id: 'client_prime',
      business_name: 'Prime Real Estate Group',
      owner_phone: '+1 (555) 678-9012',
      event_type: 'quota_exceeded',
      block_reason: 'quota_limit_exceeded',
      lead_status: '',
      order_confirmed: false,
      customer_id: '',
      from_phone: '',
      summary: 'Quota Exceeded: Client used 25,400 messages exceeding 25,000 allocated plan limit.',
      payload: { used: 25400, limit: 25000, percentage: 101.6 },
      is_read: true,
      created_at: new Date(Date.now() - 1 * 86400000).toISOString()
    }
  ];

  const auditLogs: AuditLog[] = [
    {
      id: 'aud_1',
      admin_user_id: 'usr_superadmin',
      admin_email: 'admin@example.com',
      action: 'client_created',
      entity: 'client',
      entity_id: 'client_nexus',
      before_state: null,
      after_state: { business_name: 'Nexus Cloud Technologies', plan_id: 'enterprise', status: 'active' },
      result: 'success',
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
      created_at: new Date(Date.now() - 20 * 86400000).toISOString()
    },
    {
      id: 'aud_2',
      admin_user_id: 'usr_manager',
      admin_email: 'manager@example.com',
      action: 'client_status_changed',
      entity: 'client',
      entity_id: 'client_aura',
      before_state: { status: 'active' },
      after_state: { status: 'paused', reason: 'Temporary maintenance' },
      result: 'success',
      ip_address: '192.168.1.105',
      user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      created_at: new Date(Date.now() - 2 * 86400000).toISOString()
    },
    {
      id: 'aud_3',
      admin_user_id: 'usr_superadmin',
      admin_email: 'admin@example.com',
      action: 'plan_updated',
      entity: 'plan',
      entity_id: 'professional',
      before_state: { monthly_chat_limit: 4000 },
      after_state: { monthly_chat_limit: 5000 },
      result: 'success',
      ip_address: '192.168.1.100',
      user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0',
      created_at: new Date(Date.now() - 10 * 86400000).toISOString()
    }
  ];

  return {
    adminUsers,
    adminUserCredentials: {
      'admin': '9f44f269db9b91374f4bfb07071b961b'
    },
    plans,
    clients,
    clientSettings,
    knowledgeBase,
    channelIntegrations,
    usageCounters,
    conversations,
    leadsOrders,
    adminNotifications,
    auditLogs
  };
}
